live_config_reload = true

[env]
TERM="xterm-256color"

[font]
size = 15.0

[font.normal]
family = 'JetBrainsMono Nerd Font'

[colors.cursor]
cursor = '#de935f'

[keyboard]
bindings = [
{ key = "V", mods = "Control", action = "Paste"}
]

[window.padding]
x = 10 
y = 10 
