live_config_reload = true

[env]
TERM="xterm-256color"

[font]
size = 13.0

[font.normal]
family = 'ComicCode Nerd Font'

[colors.cursor]
cursor = '#b4b7b4'

[keyboard]
bindings = [
{ key = "V", mods = "Control", action = "Paste"},
]

[window]
decorations = 'None'

[window.padding]
x = 5 
y = 5 
