
[env]
TERM="xterm-256color"

[font]
size = 11.0

[font.normal]
family = 'ComicCode Nerd Font'

[colors.cursor]
cursor = '#b4b7b4'

[keyboard]
bindings = [
{ key = "v", mods = "Control", action = "Paste"},
# { key = "t", mods = "Control", action = "CreateNewTab"},
# { key = "]", mods = "Control | Shift", action = "SelectNextTab"},
# { key = "[", mods = "Control | Shift", action = "SelectPreviousTab"},
]

[window]
decorations = 'None'

[window.padding]
x = 5 
y = 5 

[general]
live_config_reload = true
